name: Build and publish package to PyPI

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build_and_publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
      - name: Install in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]
      - name: Build
        run: python package.py --no-tests
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
