name: Build and publish package to TestPyPI

on:
  push:
    branches:
      - release-candidate

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build_and_publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to release-candidate
        uses: actions/checkout@v3
        with:
          ref: release-candidate
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
      - name: Install in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]
      - name: Build
        run: python package.py --no-tests --build-number
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
