name: Verify

on:
  push:
    branches-ignore:
      - main
      - release-candidate
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  functional:
    uses: ./.github/workflows/_tests.yaml
  packaging:
    needs: functional
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout to release-candidate
        uses: actions/checkout@v4
        with:
          ref: release-candidate
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install
        run: pip install .[build]
      - name: Package
        run: package --no-build
